### ISSUE TITLE
Problem with appcompat 26 on AndroidStudio canary 7.0

### ISSUE THREAD

**Issue by p4yam** [kngfrhzs/Interaction-Cards-Layout#2]
`Error:(246, 5) duplicate value for resource 'attr/font' with config ''
Error:(246, 5) resource previously defined here
Error:/home/payam/AndroidStudioProjects/Quotop/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:266 duplicate value for resource 'attr/font' with config ''
Error:java.lang.RuntimeException: com.android.builder.internal.aapt.AaptException: AAPT2 compile failed:`
Not sure but apparently android O added some features including  custom font support and it made trouble for many libraries including this one. Is there any way to solve this problem? I tried to disable AAPT2 but nothing changed.

**Comment by codegente** [comment]
Remove font attribute from library value file 

the attribute is written on 7th line 👍
