### ISSUE TITLE
How to change titlebar text color

### ISSUE THREAD

**Issue by narayanansampath** [kngfrhzs/Interaction-Cards-Layout#3]
How can i change the titlebar text color.

**Comment by ayaremin** [comment]
Hello @narayanansampath , there is no field for changing titlebar color because I thought that white always would be good fit for transparent overlays. In coming weeks I can add it

**Comment by narayanansampath** [comment]
Okay, Thanks for the reply.

**Comment by ayaremin** [comment]
@narayanansampath please download new version ı have added a new attribute for changing `titlebar text color`. I'm closing issue now. If you have any further question do not hesitate to ask them

**Comment by narayanansampath** [comment]
Thanks :)
